apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailhog-deployment
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      name: mailhog
  template:
    metadata:
      name: mailhog
      labels:
        name: mailhog
    spec:
      containers:
        - name: mailhog
          image: mailhog/mailhog:latest
          ports:
            - containerPort: 1025
            - containerPort: 8025
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: mailhog
spec:
  selector:
    name: mailhog
  type: ClusterIP
  ports:
    - port: 1025
      targetPort: 1025

---

apiVersion: v1
kind: Service
metadata:
  name: mailhog-public
spec:
  selector:
    name: mailhog
  type: LoadBalancer
  ports:
    - port: 8025
      targetPort: 8025